server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: clients-containers
          uri: http://clients-containers-service:8081
          predicates:
            - Path=/api/clients/**,/api/containers/**
        - id: requests-routes
          uri: http://requests-routes-service:8082
          predicates:
            - Path=/api/requests/**
        - id: trucks-depots
          uri: http://trucks-depots-service:8083
          predicates:
            - Path=/api/trucks/**,/api/depots/**
        - id: rates-costs
          uri: http://rates-costs-service:8084
          predicates:
            - Path=/api/tariffs/**,/api/costs/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/logistica
      client:
        registration:
          gateway:
            client-id: gateway
            client-secret: secret
            provider: keycloak
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/logistica
springdoc:
  api-docs:
    enabled: false
