server:
  port: 8082
spring:
  application:
    name: requests-routes-service
  datasource:
    url: jdbc:postgresql://requests-routes-db:5432/requests
    username: requests_user
    password: requests_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/logistica
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
